version: '2'

volumes:
  rails-bundle:
    driver: local
  postgres-data:
    driver: local

services:
  db:
    extends:
      file: common.yml
      service: db

    volumes:
      - postgres-data:/var/lib/postgresql/data

  core:
    build: ./evergrid_core

    volumes:
      - ./evergrid_core:/go/src/evergrid

    links:
      - db

    expose:
      - "8080"

    ports:
      - "8080:8080"

    command: bin/server

  rails:
    extends:
      file: common.yml
      service: rails

    environment:
      RAILS_ENV: development

    volumes:
      - rails-bundle:/bundle
      - ./evergrid_rails:/evergrid_rails

    links:
      - core
      - db

    command: ./start_dev.sh

    ports:
      - "80:3000"
