version: '2'

volumes:
  rails-bundle:
    driver: local
  rails-public:
    driver: local
  rails-uploads:
    driver: local
  postgres-data:
    driver: local
  logs:
    driver: local

services:
  db:
    extends:
      file: common.yml
      service: db

    # persist the database between containers by storing it in a volume
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rails:
    extends:
      file: common.yml
      service: rails

    environment:
      RAILS_ENV: production
      BUNDLE_WITHOUT: development:test

    volumes:
      - rails-bundle:/bundle
      - rails-public:/evergrid_rails/public
      - rails-uploads:/evergrid_rails/uploads
      - logs:/evergrid_rails/log

    command: ./start.sh

    expose:
      - "3000"

    links:
      - db

  # reverse proxy
  nginx:

    # set the build context to the root of the Rails app
    build: ./nginx

    # makes the web container aware of the app container
    links:
      - rails

    # use app code and precompiled assets from app container
    volumes:
      - rails-public:/evergrid_rails/public:ro
      - logs:/evergrid_rails/log

    # expose the port we configured Nginx to bind to
    ports:
      - "80:80"
